checks:
  default_service_task_name:
    enabled: true
    severity: 'error'  # 'error' for mandatory, 'warning' for optional
  validate_variables:
    enabled: true
    severity: 'warning'

fuzzy_match_threshold: 89

approved_variables_file: 'data/approved_variables.csv'

report:
  output_file: 'reports/report.html'
  template_file: 'templates/report_template.html'
